<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Restaurant.Terminal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\S02E02E04_Restaurant_Commande\S02E02E04_Restaurant_Commande.csproj" />
  </ItemGroup>

</Project>
